on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Check HTTP Status
    steps:
      - name: Check HTTP Status step
        id: httpStatus
        uses: trunkcode/check-http-status-action@v1.0.0
        with:
          skip200: true
          sitemap: '[
            "https://www.yasglobal.com/page-sitemap.xml",
            "https://www.yasglobal.com/post-sitemap.xml"
          ]'
